In [2]:
import pandas as pd

In [5]:

df = pd.read_csv(r'C:\Users\anasq\OneDrive\Desktop\Projects\F1 Lap Time Predictor\data\raw\raw_data.csv')
df

,raceId,Year,Race,Driver,Team,Lap,LapTime,Position,Compound,TyreLife,Stint,pit_duration
0,1010,2019,Australian Grand Prix,BOT,Mercedes,1,1:33.813,1,SOFT,4.0,1.0,NaN
1,1010,2019,Australian Grand Prix,BOT,Mercedes,2,1:29.662,1,SOFT,5.0,1.0,NaN
2,1010,2019,Australian Grand Prix,BOT,Mercedes,3,1:29.246,1,SOFT,6.0,1.0,NaN
3,1010,2019,Australian Grand Prix,BOT,Mercedes,4,1:28.641,1,SOFT,7.0,1.0,NaN
4,1010,2019,Australian Grand Prix,BOT,Mercedes,5,1:28.759,1,SOFT,8.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
119760,1144,2024,Abu Dhabi Grand Prix,PIA,McLaren,54,1:27.731,10,HARD,22.0,3.0,NaN
119761,1144,2024,Abu Dhabi Grand Prix,PIA,McLaren,55,1:27.781,10,HARD,23.0,3.0,NaN
119762,1144,2024,Abu Dhabi Grand Prix,PIA,McLaren,56,1:27.816,10,HARD,24.0,3.0,NaN
119763,1144,2024,Abu Dhabi Grand Prix,PIA,McLaren,57,1:28.554,10,HARD,25.0,3.0,NaN
119764,1144,2024,Abu Dhabi Grand Prix,PIA,McLaren,58,1:28.010,10,HARD,26.0,3.0,NaN

In [6]:
df.shape

(119765, 12)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119765 entries, 0 to 119764
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   raceId        119765 non-null  int64
 1   Year          119765 non-null  int64
 2   Race          119765 non-null  object
 3   Driver        119765 non-null  object
 4   Team          119765 non-null  object
 5   Lap           119765 non-null  int64
 6   LapTime       119765 non-null  object
 7   Position      119765 non-null  int64
 8   Compound      119765 non-null  object
 9   TyreLife      119765 non-null  float64
 10  Stint         119765 non-null  float64
 11  pit_duration  3779 non-null    object
dtypes: float64(2), int64(4), object(6)
memory usage: 11.0+ MB

In [9]:
df.describe()

,raceId,Year,Lap,Position,TyreLife,Stint
count,119765.000000,119765.000000,119765.000000,119765.000000,119765.000000,119765.000000
mean,1076.191216,2021.563353,30.340834,9.772730,14.879280,2.029950
std,40.812118,1.772903,18.276420,5.422632,10.434448,0.919434
min,1010.000000,2019.000000,1.000000,1.000000,1.000000,1.000000
25%,1039.000000,2020.000000,15.000000,5.000000,7.000000,1.000000
50%,1076.000000,2022.000000,29.000000,10.000000,13.000000,2.000000
75%,1114.000000,2023.000000,45.000000,14.000000,21.000000,3.000000
max,1144.000000,2024.000000,87.000000,20.000000,78.000000,7.000000

In [10]:
df.isna().sum()

raceId               0
Year                 0
Race                 0
Driver               0
Team                 0
Lap                  0
LapTime              0
Position             0
Compound             0
TyreLife             0
Stint                0
pit_duration    115986
dtype: int64

In [13]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
119760    False
119761    False
119762    False
119763    False
119764    False
Length: 119765, dtype: bool

In [13]:
import pandas as pd
from data.split_data import make_grouped_splits
from pathlib import Path

ROOT = Path.cwd().parent
DATA_DIR = ROOT / "data"
PROCESSED_DIR = DATA_DIR / "processed"
FEATURES_DIR = DATA_DIR / "features"

df = pd.read_csv(FEATURES_DIR / r"telemetry_features.csv")

train_df, val_df, test_df = make_grouped_splits(df, target_col='laptime')

C:\Users\anasq\AppData\Local\Temp\ipykernel_12360\3771108670.py:10: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(FEATURES_DIR / r"telemetry_features.csv")

In [14]:
train_df

,raceid,year,race,driver,team,lap,compound,tyrelife,stint,position,...,pit_flag,stint_progress,previous_position,position_change,previous_lap_special_flag,is_in_lap_flag,is_out_lap_flag,is_lap1_flag,laptime,group_id
0,1010,2019,Australian Grand Prix,ALB,Toro Rosso,1,SOFT,1.0,1.0,11,...,0,0.076923,0.0,0.0,0.0,0,0,1,101.759,1010_ALB
1,1010,2019,Australian Grand Prix,ALB,Toro Rosso,2,SOFT,2.0,1.0,11,...,0,0.153846,11.0,0.0,1.0,0,0,0,91.716,1010_ALB
2,1010,2019,Australian Grand Prix,ALB,Toro Rosso,3,SOFT,3.0,1.0,11,...,0,0.230769,11.0,0.0,0.0,0,0,0,91.357,1010_ALB
3,1010,2019,Australian Grand Prix,ALB,Toro Rosso,4,SOFT,4.0,1.0,11,...,0,0.307692,11.0,0.0,0.0,0,0,0,91.421,1010_ALB
4,1010,2019,Australian Grand Prix,ALB,Toro Rosso,5,SOFT,5.0,1.0,11,...,0,0.384615,11.0,0.0,0.0,0,0,0,90.884,1010_ALB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109783,1144,2024,Abu Dhabi Grand Prix,ZHO,Sauber,53,HARD,14.0,3.0,14,...,0,0.777778,14.0,0.0,0.0,0,0,0,88.483,1144_ZHO
109784,1144,2024,Abu Dhabi Grand Prix,ZHO,Sauber,54,HARD,15.0,3.0,14,...,0,0.833333,14.0,0.0,0.0,0,0,0,88.022,1144_ZHO
109785,1144,2024,Abu Dhabi Grand Prix,ZHO,Sauber,55,HARD,16.0,3.0,14,...,0,0.888889,14.0,0.0,0.0,0,0,0,88.047,1144_ZHO
109786,1144,2024,Abu Dhabi Grand Prix,ZHO,Sauber,56,HARD,17.0,3.0,14,...,0,0.944444,14.0,0.0,0.0,0,0,0,87.982,1144_ZHO
109787,1144,2024,Abu Dhabi Grand Prix,ZHO,Sauber,57,HARD,18.0,3.0,14,...,0,1.000000,14.0,0.0,0.0,0,0,0,88.374,1144_ZHO

In [15]:
val_df

,raceid,year,race,driver,team,lap,compound,tyrelife,stint,position,...,pit_flag,stint_progress,previous_position,position_change,previous_lap_special_flag,is_in_lap_flag,is_out_lap_flag,is_lap1_flag,laptime,group_id
700,1010,2019,Australian Grand Prix,RAI,Alfa Romeo,1,SOFT,4.0,1.0,9,...,0,0.285714,0.0,0.0,0.0,0,0,1,100.507,1010_RAI
701,1010,2019,Australian Grand Prix,RAI,Alfa Romeo,2,SOFT,5.0,1.0,9,...,0,0.357143,9.0,0.0,1.0,0,0,0,91.184,1010_RAI
702,1010,2019,Australian Grand Prix,RAI,Alfa Romeo,3,SOFT,6.0,1.0,9,...,0,0.428571,9.0,0.0,0.0,0,0,0,90.928,1010_RAI
703,1010,2019,Australian Grand Prix,RAI,Alfa Romeo,4,SOFT,7.0,1.0,9,...,0,0.500000,9.0,0.0,0.0,0,0,0,90.596,1010_RAI
704,1010,2019,Australian Grand Prix,RAI,Alfa Romeo,5,SOFT,8.0,1.0,9,...,0,0.571429,9.0,0.0,0.0,0,0,0,90.765,1010_RAI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109023,1144,2024,Abu Dhabi Grand Prix,DOO,Alpine F1 Team,53,HARD,31.0,2.0,15,...,0,0.885714,15.0,0.0,0.0,0,0,0,89.717,1144_DOO
109024,1144,2024,Abu Dhabi Grand Prix,DOO,Alpine F1 Team,54,HARD,32.0,2.0,15,...,0,0.914286,15.0,0.0,0.0,0,0,0,89.539,1144_DOO
109025,1144,2024,Abu Dhabi Grand Prix,DOO,Alpine F1 Team,55,HARD,33.0,2.0,15,...,0,0.942857,15.0,0.0,0.0,0,0,0,89.647,1144_DOO
109026,1144,2024,Abu Dhabi Grand Prix,DOO,Alpine F1 Team,56,HARD,34.0,2.0,15,...,0,0.971429,15.0,0.0,0.0,0,0,0,89.121,1144_DOO
109027,1144,2024,Abu Dhabi Grand Prix,DOO,Alpine F1 Team,57,HARD,35.0,2.0,15,...,0,1.000000,15.0,0.0,0.0,0,0,0,89.566,1144_DOO

In [16]:
test_df

,raceid,year,race,driver,team,lap,compound,tyrelife,stint,position,...,pit_flag,stint_progress,previous_position,position_change,previous_lap_special_flag,is_in_lap_flag,is_out_lap_flag,is_lap1_flag,laptime,group_id
114,1010,2019,Australian Grand Prix,GAS,Red Bull,1,MEDIUM,1.0,1.0,17,...,0,0.027778,0.0,0.0,0.0,0,0,1,105.008,1010_GAS
115,1010,2019,Australian Grand Prix,GAS,Red Bull,2,MEDIUM,2.0,1.0,16,...,0,0.055556,17.0,-1.0,1.0,0,0,0,91.585,1010_GAS
116,1010,2019,Australian Grand Prix,GAS,Red Bull,3,MEDIUM,3.0,1.0,16,...,0,0.083333,16.0,0.0,0.0,0,0,0,91.406,1010_GAS
117,1010,2019,Australian Grand Prix,GAS,Red Bull,4,MEDIUM,4.0,1.0,16,...,0,0.111111,16.0,0.0,0.0,0,0,0,92.361,1010_GAS
118,1010,2019,Australian Grand Prix,GAS,Red Bull,5,MEDIUM,5.0,1.0,16,...,0,0.138889,16.0,0.0,0.0,0,0,0,91.171,1010_GAS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109400,1144,2024,Abu Dhabi Grand Prix,NOR,McLaren,54,HARD,28.0,2.0,1,...,0,0.875000,1.0,0.0,0.0,0,0,0,88.124,1144_NOR
109401,1144,2024,Abu Dhabi Grand Prix,NOR,McLaren,55,HARD,29.0,2.0,1,...,0,0.906250,1.0,0.0,0.0,0,0,0,87.647,1144_NOR
109402,1144,2024,Abu Dhabi Grand Prix,NOR,McLaren,56,HARD,30.0,2.0,1,...,0,0.937500,1.0,0.0,0.0,0,0,0,87.698,1144_NOR
109403,1144,2024,Abu Dhabi Grand Prix,NOR,McLaren,57,HARD,31.0,2.0,1,...,0,0.968750,1.0,0.0,0.0,0,0,0,87.929,1144_NOR
109404,1144,2024,Abu Dhabi Grand Prix,NOR,McLaren,58,HARD,32.0,2.0,1,...,0,1.000000,1.0,0.0,0.0,0,0,0,89.858,1144_NOR